[package]
name = "websocket-nvim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { version = "0.4.2", features = ["neovim-0-9", "libuv"] }
serde = "1.0.201"